# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/users/alu07/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/ip/Memory/Memory.xci
# IP: The module: 'Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/users/alu07/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/ip/Memory/Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/users/alu07/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/ip/Memory/Memory.xci
# IP: The module: 'Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/users/alu07/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/ip/Memory/Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
