# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.cache/wt [current_project]
set_property parent.project_path /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property loop_count 500 [current_fileset]
add_files /home/miguelan/Escritorio/MiniMIPS/assets/Bubblesort.coe
read_vhdl -library xil_defaultlib {
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/ALU.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/ALUControl.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/ControlFSM.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/Display7_Segmentos.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/DivFreq.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/InstructionRegister.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/MIPS.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/RegParallel.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/RegisterFile.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/ShiftL2.vhd
  /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/new/Manager.vhd
}
read_ip -quiet /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/ip/Memory/Memory.xci
set_property used_in_implementation false [get_files -all /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/sources_1/ip/Memory/Memory_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/constrs_1/new/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files /home/miguelan/Escritorio/MiniMIPS/miniMIPS/miniMIPS.srcs/constrs_1/new/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Manager -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Manager.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Manager_utilization_synth.rpt -pb Manager_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
